spring.application.name=demo-for-amancoding

spring.datasource.url=jdbc:postgresql://localhost:5432/aman_db
spring.datasource.username=postgres
spring.datasource.password=Root
spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 🔐 JWT CONFIG
# Secret key ko thoda aur lamba karein (Min 32-64 characters safe rehte hain)
jwt.secret=MySuperSecretKeyForJWT1234567890_ExtraSecureStringForAmanCoding

# Access Token Expiry: 24 Hours (1000 * 60 * 60 * 24)
jwt.access-token.expiration=86400000

# Refresh Token Expiry: 7 Days
jwt.refresh-token.expiration=604800000

server.error.include-message=always