spring.application.name=demo-for-amancoding

# Render PostgreSQL Configuration (Ye values Render dashboard se aayengi)
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 🔐 JWT CONFIG
# Secret key ko thoda aur lamba karein (Min 32-64 characters safe rehte hain)
jwt.secret=MySuperSecretKeyForJWT1234567890_ExtraSecureStringForAmanCoding

# Access Token Expiry: 24 Hours (1000 * 60 * 60 * 24)
jwt.access-token.expiration=86400000

# Refresh Token Expiry: 7 Days
jwt.refresh-token.expiration=604800000

server.error.include-message=always